# Generated by Django 4.0.1 on 2022-01-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dragon', models.CharField(default='Unknown', max_length=64)),
                ('title', models.CharField(default='Unkown', max_length=256)),
                ('color', models.CharField(default='None', max_length=48)),
                ('age', models.CharField(choices=[('egg', 'EGG'), ('yearling', 'YEARLING'), ('immature', 'IMMATURE'), ('adult', 'ADULT'), ('great', 'GREAT'), ('Ancient', 'ANCIENT')], default='adult', max_length=8)),
                ('estimated_height', models.IntegerField(max_length=3)),
                ('spotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
