# Generated by Django 4.0.1 on 2022-01-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_rater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='estimated_height',
            field=models.IntegerField(),
        ),
    ]
