# Generated by Django 4.0.1 on 2022-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_rater', '0002_alter_dragon_estimated_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='descritption',
            field=models.TextField(default=''),
        ),
    ]
