# Generated by Django 4.0.1 on 2022-01-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_rater', '0003_dragon_descritption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='descritption',
            field=models.TextField(),
        ),
    ]
