# Generated by Django 4.0.1 on 2022-01-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragon_rater', '0004_alter_dragon_descritption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dragon',
            old_name='descritption',
            new_name='descritption_of_dragon',
        ),
    ]
